### PR TITLE
Update to Rust 2018 edition

### LINKED ISSUE #139: Update to Rust 2018 edition

### PR DESCRIPTION
**Pull request by 1011X**
Fixes #139.

The compiler also said that the `custom_derive` feature was removed and subsumed by `#[proc_macro_derive]`, but it compiled fine without the attribute. Do I leave it out or should I place it somewhere?

### CODE REVIEW

**Comment by barzamin** [comment]
i think it's fine to leave off since everything we depend has switched from `custom_derive` to `proc_macro`, afaik.

**Comment by barzamin** [comment]
can you `cargo fmt` your code? and, if it's not too much trouble, bring the stuff in `libs/` up to edition-2018 as well?

**Comment by 1011X** [comment]
Sure, I'll try doing that now

**Comment by barzamin** [comment]
Everything's green and the diff looks good; I'm going to merge. Thanks so much for the PR!

**Comment by 1011X** [comment]
You're very welcome~ !

**Pull request merged**
