### PR TITLE
ui: added CW toggle and post

### LINKED ISSUE #33: Content warnings
- [x] Schema column for content warnings on statuses
- [x] Serialization of content warning field to `"summary"` property on AP status objects
- [x] UI for adding CWs to a status when composing (basically just add a form field and make `content_warning` `None` if it's empty and `Some(_)` otherwise)
- [x] UI for displaying CWs on statuses on the profile page and status pages

this is seriously a pretty small change change! things you might want to do:
- [x] factor out the status display logic from the profile and status pages to a single source
- [x] figure out how to do CSS-only content 'show more' content collapses

@dexamphetamine, you wanted something to work on; this might be a great opportunity!

### PR DESCRIPTION
**Pull request by dexamphetamine**
closes #33

works, just needs:

- [x] reorganizing templating code to be less of a mess
- [x] cws on profile pages

i put the CW reveal styling in a separate file because it's hacky and should probably go away down the road.

### CODE REVIEW

**Comment by barzamin** [comment]
Build is failing right now, but only due to rustfmt.

Not having tests isn't a big deal atm; _nothing_ is actually really tested, and I think we should just go back and do that for other stuff first.

**Comment by dexamphetamine** [comment]
how were you thinking breaking out the templating files? by page view, maybe?

**Comment by barzamin** [comment]
Note statuses are displayed in a list on user profile pages; you'll need to account for that.

**Comment by barzamin** [comment]
@dexamphetamine yes, I'm strongly considering this

**Comment by barzamin** [comment]
I'm going to rewrite the collapsing bit with [this code](https://alligator.io/css/collapsible/), I think.

**Comment by barzamin** [comment]
Rebased against master and force-pushed.

**Comment by barzamin** [comment]
I have the collapse code done; I'll push in an hour or two when I get back home.

**Pull request merged**
