### PR TITLE
Cucumber

### PR DESCRIPTION
**Pull request by netshade**
After #70 got merged, @ashkitten found some regressions caused by not correctly marking the content as "safe" that was being emitted by the bio transformer ( #73 ). 

This seemed like a potentially good spot for integration tests, so I've done the initial work on integrating Cucumber and writing some basic smoke tests for ensuring functionality. I've tried to stay at a high level and just capture the basics. 

The suite is configured to run with the `chromedriver` headless browser, which you can install via `brew install chromedriver` ( you may need to tap the cask for this ) or [following the official install instructions](http://chromedriver.chromium.org/getting-started).

Marked WIP due:

- [ ] Not a requested part of the app, any further work should hold until this thought desirable
- [ ] README should be adjusted with further instructions to exercise test suite
- [ ] Potentially included in Travis CI runs, configuration for same required

Functional notes:
1. The suite takes a while to run.  ( 3 min on my MBP ).
1. I had to do some slightly kludgy work to ensure the database is clean between scenarios, see `features/support/env.rb`
1. The suite is invoked via `scripts/cucumber`, as we need to ensure that the app is built, running on the expected port, and that the necessary env details are passed through before starting the actual cucumber run. Any arguments passed to `scripts/cucumber` are passed along to cucumber proper however, so individual scenarios may be run a la `scripts/cucumber path/to/the.feature:23`.

### CODE REVIEW

**Comment by netshade** [comment]
Any thoughts on this? Worth continuing on?

**Comment by yipdw** [comment]
Hmm.  I appreciate the effort, but in my experience, Cucumber scenarios are usually one of the first things to rot, especially in projects early in their life when the interface is rapidly changing.  It is possible to combat that rot by requiring a full scenario run before integration, but 3 minutes is a very long time to wait.

Is there some other way to add an effective regression test for the error that motivated this?

**Comment by netshade** [comment]
I had difficulty finding one that seemed like it was the right fit - I saw lots of "isolated integration testing", eg, make the responsibility of the session and browser state the application's problem, and just issue HTTP requests. That part seemed less than ideal to me, in that the tests would be decoupled from how the application actually worked, which seemed to defeat the purpose of the suite.

Definitely take your point tho - tests in general are prone to rot w/o upkeep, and tests that folks are not inclined to run even more so.

**Comment by netshade** [comment]
Seemed like an even balance of opinions on this, one positive, one negative, and I'm mostly indifferent. That being the case, just going to close.

**Comment by netshade** [comment]
( Historical note: according to Travis CI runs, test times vary from 5 to 10 minutes. It would likely be safe to assume that the 3min MBP run time is presumed as what would be the unlikeliest of best cases on Travis CI. )

**Pull request closed without merging**
