### PR TITLE
Bikeshed rustfmt config

### PR DESCRIPTION
**Pull request by barzamin**
See #8.

/cc @ilianaw

### CODE REVIEW

**Comment by ilianaw** [comment]
Here are the changes that config appears to result in: https://gist.github.com/ilianaw/5c1502ea658cf82d52909d1a5516d61b

**Comment by barzamin** [comment]
Yep, I've been running it and I'm not especially happy with that configuration; I have a newer one that I'll push in a bit. @ashkitten pointed out that I should probably try to stay pretty close to normal rustfmt behavior just because rustfmt configuration is somewhat unstable.

**Comment by barzamin** [comment]
The current config results in these changes: https://gist.github.com/barzamin/3dfcd40c10cecf5b8738514a35d924e8

**Comment by barzamin** [comment]
The current config results in these changes: https://gist.github.com/barzamin/7d4ed14773624762efb191672886ea2a

**Pull request merged**
